The system is divided into two main components: a React-based frontend and a .NET Web API backend. Together, these components communicate over REST endpoints and share a simple CSV file for storage, providing an easy-to-run solution without requiring a traditional database.

The frontend is built using React and organized into two primary views: the Student page and the Professor page. The Student page allows users to enter their name, choose whether they are clocking in or out, retrieve their current GPS location, and submit the attendance record; they can also search for their attendance records. It performs input validation, displays helpful status messages, and communicates with the backend through a POST request to the student clock endpoint. The Professor page serves as the administrative interface, allowing instructors to display all attendance records, search for entries by student name, and toggle visibility of the results. This page communicates with the backend through GET requests to retrieve full or filtered attendance data. Both pages use modern ETSU-themed styling to provide a clean and recognizable interface. 

The backend is implemented using ASP.NET Core Web API and follows a clean separation between controllers and service classes. The StudentProcessor service handles incoming attendance submissions, generating timestamps and writing each record to a CSV file stored in the user’s Downloads folder. The ProfessorProcessor service reads from this same file and supports filtering by student name or date range. Controller endpoints expose this functionality to the frontend using standard JSON-based REST responses. This architecture keeps logic modular and easy to extend while remaining simple enough for quicker development and testing.

Instead of using a database, the system stores all attendance data in a single CSV file named “StudentClockRecords.csv”. This file contains each entry’s timestamp, student name, action type, and GPS coordinates. Using a CSV file keeps the system lightweight, portable, and simple to deploy on any environment without additional configuration.

Overall, this project demonstrates a clean full-stack workflow where a React frontend collects user input, sends structured data to a .NET backend, and retrieves stored information for display. The use of REST APIs, modular services, and lightweight file-based storage creates a flexible architecture that demonstrates full-stack system design.
